import { Skill } from '@/features/project-showcase/types/skill';

export const skillIcons: ReadonlyMap<Skill, string> = new Map([
  [
    Skill.Haskell,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/haskell/haskell-plain.svg',
  ],
  [
    Skill.TypeScript,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-plain.svg',
  ],
  [
    Skill.JavaScript,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-plain.svg',
  ],
  [
    Skill.CSS,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-plain.svg',
  ],
  [
    Skill.Sass,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg',
  ],
  [
    Skill.HTML,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-plain.svg',
  ],
  [
    Skill.React,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg',
  ],
  [
    Skill.NextJS,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-plain.svg',
  ],
  [
    Skill.Elixir,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/elixir/elixir-plain.svg',
  ],
  [
    Skill.CSharp,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/csharp/csharp-plain.svg',
  ],
  [
    Skill.FSharp,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fsharp/fsharp-plain.svg',
  ],
  [
    Skill.C,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-plain.svg',
  ],
  [
    Skill.CPlusPlus,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-plain.svg',
  ],
  [
    Skill.Godot,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/godot/godot-plain.svg',
  ],
  [
    Skill.Unity,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/unity/unity-plain.svg',
  ],
  [
    Skill.Python,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-plain.svg',
  ],
  [
    Skill.Ruby,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ruby/ruby-plain.svg',
  ],
  [
    Skill.Java,
    'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-plain.svg',
  ],
]);
